version: '3'
services:
  backend:
    build: ./backend
    container_name: packepfecam
    env_file:
      - ./.env
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/
  